language: python
python:
  - 3.6
install:
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install .
script:
  - pytest --cov=./
after_success:
  - codecov
before_install:
  - chmod +x setup.py
